export enum ROUTES {
  Home = "/",
  Auth = "/auth",
  Login = "/auth/login",
  SignUp = "/auth/signup",
  Catalog = "/catalog",
  Beat = "/beat",
  DynamicBeat = "/beat/:id",
  DynamicBeatEdit = "/beat/:id/edit",
  Upload = "/upload",
  UploadBeats = "/upload/beats",
  UploadTags = "/upload/tags",
  Cart = "/cart",
  Invalid = "*",
}
